services:
  casamiento-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casamiento-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GOOGLE_SCRIPT_URL=${GOOGLE_SCRIPT_URL}
    env_file:
      - .env.local
